//! `reverse` command — clone a remote Git repo and generate a `plan.toml`
//! skeleton from its contents + user-supplied hints.
//!
//! Inspired by [filiksyos/gitreverse](https://github.com/filiksyos/gitreverse):
//! the repo-fetching idea is borrowed, but the output is a structured
//! Wiggum `plan.toml` (not a single vibe-coding prompt).
//!
//! # Flow
//!
//! 1. Clone `<url>` into a tempdir (`git clone --depth=1`).
//! 2. Re-use [`crate::adapters::bootstrap::scan_project`] on that tempdir.
//! 3. Load and merge `--hints` (TOML or Markdown) into the scan result.
//! 4. Render a `Plan` via [`crate::adapters::bootstrap::build_plan_from_scan`]
//!    with the merged scan, then write it to `--output`.

pub mod fetch;
pub mod hints;
pub mod llm;

use std::path::{Path, PathBuf};

use crate::adapters::bootstrap::{self, ScanResult};
use crate::domain::plan::{Phase, Plan};
use crate::error::{Result, WiggumError};

/// Options that control how `wiggum reverse` runs.
#[derive(Debug, Clone)]
pub struct ReverseOptions {
    /// Remote URL (e.g. `https://github.com/owner/repo` or `git@github.com:owner/repo.git`).
    pub url: String,
    /// Optional hints file (TOML or Markdown, detected by extension).
    pub hints: Option<PathBuf>,
    /// Path to write the generated plan (defaults to `<cwd>/plan.toml`).
    pub output: PathBuf,
    /// Overwrite an existing plan file without prompting.
    pub force: bool,
    /// Keep the cloned tempdir after generation (for debugging).
    pub keep_tmp: bool,
    /// Scope the clone + scan to a specific subfolder of the repo. Overrides
    /// any `/tree/<branch>/<path>` subfolder encoded in the URL.
    pub subdir: Option<String>,
    /// Prefer the GitHub REST API for fetching the repo. Falls back to
    /// `git clone` on rate-limit / non-GitHub URL / missing token.
    pub github_api: bool,
    /// Use an LLM to decompose the repo into intelligent phases + tasks.
    /// `Some(provider)` activates the LLM pass (provider = "anthropic" or "minimax").
    pub llm: Option<String>,
    /// Override the LLM model name (provider-specific).
    pub llm_model: Option<String>,
    /// Override the LLM API key (otherwise read from `<PROVIDER>_API_KEY`).
    pub api_key: Option<String>,
}

/// Run `wiggum reverse` end-to-end.
///
/// # Errors
///
/// Returns an error if:
/// - the URL cannot be cloned (network failure, auth failure, non-git URL),
/// - the hints file cannot be parsed,
/// - no language can be detected in the cloned repo,
/// - the output file already exists and `--force` was not passed,
/// - the LLM pass is enabled but the API key is missing/invalid,
/// - the LLM returns a malformed plan that we can't recover from.
pub fn run_reverse(opts: &ReverseOptions) -> Result<PathBuf> {
    if opts.output.exists() && !opts.force {
        return Err(WiggumError::Validation(format!(
            "{} already exists (use --force to overwrite)",
            opts.output.display()
        )));
    }

    println!("🦝 wiggum reverse — {}", opts.url);

    // Resolve subdir: explicit `--subdir` wins over URL-encoded.
    let subdir = opts
        .subdir
        .clone()
        .or_else(|| fetch::parse_github_subdir(&opts.url));

    // Clone (always — the LLM pass benefits from having the actual files,
    // not just metadata).
    let clone = if let Some(sub) = subdir.as_deref() {
        println!("  sparse-cloning subdir: {sub}");
        fetch::clone_sparse_subdir(&opts.url, sub)?
    } else {
        fetch::clone_shallow(&opts.url)?
    };

    let result = generate_plan(&clone.path, opts.hints.as_deref(), opts);

    // Always clean up the tempdir unless the user explicitly asked to keep it.
    if opts.keep_tmp {
        println!("\n📂 Cloned source kept at {}", clone.path.display());
        // Leak the TempDir by dropping the guard but reading the path first.
        // (TempDir deletes on Drop; we just keep `path` printed above.)
    } else {
        drop(clone.guard);
    }

    let (plan, scan_summary) = result?;

    bootstrap::print_scan_summary(&scan_summary, Path::new("<repo>"));

    let toml_content = toml::to_string_pretty(&plan)
        .map_err(|e| WiggumError::Validation(format!("serialize plan: {e}")))?;
    let content = format!(
        "# Generated by `wiggum reverse {}` — fill in phases and tasks below\n\n{toml_content}",
        opts.url
    );

    std::fs::write(&opts.output, content)?;

    println!("\n✅ Plan saved to {}", opts.output.display());
    println!(
        "\nNext: edit the plan to add phases and tasks, then run `wiggum generate {}`",
        opts.output.display()
    );

    Ok(opts.output.clone())
}

/// Clone the repo, scan it, load hints, merge, and build a `Plan`.
fn generate_plan(
    repo_path: &Path,
    hints_path: Option<&Path>,
    opts: &ReverseOptions,
) -> Result<(Plan, ScanResult)> {
    let mut scan = bootstrap::scan_project(repo_path)?;

    let loaded_hints = if let Some(path) = hints_path {
        let bytes = std::fs::read(path).map_err(|e| {
            WiggumError::Validation(format!("read hints file {}: {e}", path.display()))
        })?;
        let text = String::from_utf8_lossy(&bytes);
        Some(hints::parse_hints(&text, path)?)
    } else {
        None
    };

    if let Some(h) = &loaded_hints {
        apply_hints(&mut scan, h);
    }

    let mut plan = bootstrap::build_plan_from_scan(&scan, Path::new("<repo>"));
    if let Some(h) = &loaded_hints {
        apply_hints_to_plan(&mut plan, h);
    }
    // <repo> is a placeholder so build_plan_from_scan has *something* to fill in
    // for project.path; the user will override it via their plan once generated.
    // But we want it to reflect the actual repo they're targeting, so overwrite:
    plan.project.path = "<repo>".to_string();

    // Optional LLM pass — replaces the placeholder phases with intelligent ones.
    if let Some(provider_str) = &opts.llm {
        if let Some(provider) = llm::Provider::from_cli(provider_str) {
            // We have to do async work in a sync function — use a tiny runtime.
            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .map_err(|e| {
                    WiggumError::Validation(format!("build tokio runtime for LLM call: {e}"))
                })?;
            let key = provider.resolve_api_key(opts.api_key.as_deref())?;
            let client = llm::build_client(provider, key);
            let model = opts
                .llm_model
                .clone()
                .unwrap_or_else(|| provider.default_model().to_string());
            println!("  🧠 LLM phase decomposition via {provider} ({model})…");
            let resp = rt.block_on(llm::decompose_into_plan(
                client,
                repo_path,
                &scan,
                loaded_hints.as_ref(),
                &mut plan,
            ))?;
            println!(
                "     ↳ {} input + {} output tokens",
                resp.input_tokens, resp.output_tokens
            );
        } else {
            return Err(WiggumError::Validation(format!(
                "unknown --llm provider '{provider_str}' (expected anthropic or minimax)"
            )));
        }
    }

    Ok((plan, scan))
}

/// Apply hint overrides to the raw scan result.
fn apply_hints(scan: &mut ScanResult, h: &hints::Hints) {
    if let Some(lang) = h.project.language {
        scan.language = lang;
    }
    if let Some(name) = &h.project.name {
        scan.name.clone_from(name);
    }
    if let Some(desc) = &h.project.description {
        scan.description.clone_from(desc);
    }
    if let Some(arch) = &h.project.architecture {
        scan.architecture = Some(arch.clone());
    }
    // Freeform rules always get appended, never replace.
    for rule in &h.project.extra_rules {
        if !scan.rules.contains(rule) {
            scan.rules.push(rule.clone());
        }
    }
}

/// Apply hint overrides to the assembled `Plan` (post `build_plan_from_scan`).
fn apply_hints_to_plan(plan: &mut Plan, h: &hints::Hints) {
    // Persona override (or default fallback to detected-language persona).
    if let Some(persona) = &h.orchestrator.persona {
        plan.orchestrator.persona.clone_from(persona);
    }
    if let Some(strategy) = h.orchestrator.strategy {
        plan.orchestrator.strategy = strategy;
    }
    if let Some(max) = h.orchestrator.max_retries {
        plan.orchestrator.max_retries = max;
    }
    if let Some(on_failure) = h.orchestrator.on_failure {
        plan.orchestrator.on_failure = on_failure;
    }
    for rule in &h.orchestrator.extra_rules {
        if !plan.orchestrator.rules.contains(rule) {
            plan.orchestrator.rules.push(rule.clone());
        }
    }

    // Add any pre-declared phases/tasks. If the user provided their own
    // phases, drop the placeholder "TODO — rename this phase" that
    // `build_plan_from_scan` injected — the user has explicitly chosen
    // a structure, so the placeholder is just noise.
    if !h.phases.is_empty() {
        plan.phases.retain(|p| !is_bootstrap_placeholder_phase(p));
        let start = plan.phases.iter().map(|p| p.order).max().unwrap_or(0) + 1;
        for (next, ph) in (start..).zip(h.phases.iter()) {
            let phase = Phase {
                order: next,
                name: ph.name.clone(),
                tasks: ph
                    .tasks
                    .iter()
                    .map(|t| crate::domain::plan::TaskDef {
                        slug: t.slug.clone(),
                        title: t.title.clone(),
                        goal: t.goal.clone(),
                        depends_on: t.depends_on.clone(),
                        hints: t.hints.clone(),
                        test_hints: Vec::new(),
                        must_haves: Vec::new(),
                        gate: t.gate.clone(),
                        evaluation_criteria: Vec::new(),
                        kind: crate::domain::plan::TaskKind::default(),
                    })
                    .collect(),
            };
            plan.phases.push(phase);
        }
    }

    // Reapply preflight defaults now that language may have been overridden.
    plan.preflight = plan.preflight.clone().with_defaults(plan.project.language);
}

/// Detect the placeholder phase that `bootstrap::build_plan_from_scan` injects,
/// so the reverse command can drop it when the user has supplied real phases.
fn is_bootstrap_placeholder_phase(p: &Phase) -> bool {
    p.name == "TODO — rename this phase"
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::indexing_slicing)]
mod tests {
    use super::*;
    use crate::adapters::reverse::hints::{
        Hints, OrchestratorHints, PhaseHints, ProjectHints, TaskHints,
    };
    use crate::domain::plan::{FailureAction, Strategy};

    fn empty_hints() -> Hints {
        Hints::default()
    }

    #[test]
    fn apply_hints_overrides_language_and_arch() {
        let mut scan = bootstrap::ScanResult {
            language: crate::domain::plan::Language::Rust,
            name: "scanned-name".to_string(),
            description: "scanned desc".to_string(),
            architecture: Some("hexagonal".to_string()),
            rules: vec!["existing rule".to_string()],
            has_tests: false,
            has_ci: false,
        };

        let hints = Hints {
            project: ProjectHints {
                language: Some(crate::domain::plan::Language::Go),
                architecture: Some("ddd".to_string()),
                extra_rules: vec!["Use latest stable Go".to_string()],
                ..Default::default()
            },
            ..empty_hints()
        };

        apply_hints(&mut scan, &hints);

        assert!(matches!(scan.language, crate::domain::plan::Language::Go));
        assert_eq!(scan.architecture.as_deref(), Some("ddd"));
        assert!(scan.rules.contains(&"existing rule".to_string()));
        assert!(scan.rules.contains(&"Use latest stable Go".to_string()));
    }

    #[test]
    fn apply_hints_does_not_duplicate_existing_rules() {
        let mut scan = bootstrap::ScanResult {
            language: crate::domain::plan::Language::Rust,
            name: "x".to_string(),
            description: String::new(),
            architecture: None,
            rules: vec!["Use latest stable Go".to_string()],
            has_tests: false,
            has_ci: false,
        };
        let hints = Hints {
            project: ProjectHints {
                extra_rules: vec!["Use latest stable Go".to_string()],
                ..Default::default()
            },
            ..empty_hints()
        };
        apply_hints(&mut scan, &hints);
        // The hint rule was already present — should still appear exactly once.
        let count = scan
            .rules
            .iter()
            .filter(|r| r.as_str() == "Use latest stable Go")
            .count();
        assert_eq!(count, 1);
    }

    #[test]
    fn apply_hints_to_plan_sets_persona_and_strategy() {
        let mut plan = make_empty_plan();
        let hints = Hints {
            orchestrator: OrchestratorHints {
                persona: Some("Senior Go engineer".to_string()),
                strategy: Some(Strategy::Complete),
                max_retries: Some(5),
                on_failure: Some(FailureAction::Escalate),
                extra_rules: vec!["Run `go vet`".to_string()],
            },
            ..empty_hints()
        };
        apply_hints_to_plan(&mut plan, &hints);
        assert_eq!(plan.orchestrator.persona, "Senior Go engineer");
        assert!(matches!(plan.orchestrator.strategy, Strategy::Complete));
        assert_eq!(plan.orchestrator.max_retries, 5);
        assert!(matches!(
            plan.orchestrator.on_failure,
            FailureAction::Escalate
        ));
        assert!(
            plan.orchestrator
                .rules
                .contains(&"Run `go vet`".to_string())
        );
    }

    #[test]
    fn apply_hints_to_plan_appends_phases() {
        let mut plan = make_empty_plan();
        let hints = Hints {
            phases: vec![
                PhaseHints {
                    name: "Domain".to_string(),
                    tasks: vec![TaskHints {
                        slug: "aggregates".to_string(),
                        title: "Define aggregates".to_string(),
                        goal: "Identify aggregates".to_string(),
                        ..Default::default()
                    }],
                },
                PhaseHints {
                    name: "Infra".to_string(),
                    tasks: vec![],
                },
            ],
            ..empty_hints()
        };
        apply_hints_to_plan(&mut plan, &hints);
        assert_eq!(plan.phases.len(), 2);
        assert_eq!(plan.phases[0].name, "Domain");
        assert_eq!(plan.phases[0].order, 1);
        assert_eq!(plan.phases[1].name, "Infra");
        assert_eq!(plan.phases[1].order, 2);
        assert_eq!(plan.phases[0].tasks[0].slug, "aggregates");
    }

    fn make_empty_plan() -> Plan {
        use crate::domain::plan::{
            IntegrationConfig, Orchestrator, Preflight, Project, SecurityConfig, StyleConfig,
            TargetConfig,
        };
        Plan {
            project: Project {
                name: "x".to_string(),
                description: String::new(),
                language: crate::domain::plan::Language::Rust,
                path: "<repo>".to_string(),
                architecture: None,
            },
            preflight: Preflight::default(),
            orchestrator: Orchestrator::default(),
            evaluator: None,
            security: SecurityConfig::default(),
            integration: IntegrationConfig::default(),
            style: StyleConfig::default(),
            targets: TargetConfig::default(),
            phases: Vec::new(),
        }
    }
}
