use std::path::{Path, PathBuf};

use crate::domain::plan::{
    Language, Orchestrator, Phase, Plan, Preflight, Project, Strategy, TaskDef,
};
use crate::error::{Result, WiggumError};

/// Result of scanning an existing project directory.
#[derive(Debug)]
pub struct ScanResult {
    pub language: Language,
    pub name: String,
    pub description: String,
    pub architecture: Option<String>,
    pub rules: Vec<String>,
    pub has_tests: bool,
    pub has_ci: bool,
}

/// Scan a project directory and generate a skeleton plan TOML.
///
/// # Errors
///
/// Returns an error if the directory does not exist, no language is detected,
/// or the plan file cannot be written.
pub fn run_bootstrap(project_path: &Path, output: Option<&Path>, force: bool) -> Result<PathBuf> {
    let project_path = project_path
        .canonicalize()
        .map_err(|e| WiggumError::Validation(format!("cannot resolve path: {e}")))?;

    let plan_path = output.map_or_else(|| project_path.join("plan.toml"), Path::to_path_buf);

    if plan_path.exists() && !force {
        return Err(WiggumError::Validation(format!(
            "{} already exists (use --force to overwrite)",
            plan_path.display()
        )));
    }

    let scan = scan_project(&project_path)?;

    print_scan_summary(&scan, &project_path);

    let plan = build_plan_from_scan(&scan, &project_path);

    let toml_content =
        toml::to_string_pretty(&plan).map_err(|e| WiggumError::Validation(e.to_string()))?;

    // Prepend a comment header
    let content = format!(
        "# Generated by `wiggum bootstrap` — fill in phases and tasks below\n\n{toml_content}"
    );
    std::fs::write(&plan_path, content)?;

    println!("\n✅ Plan saved to {}", plan_path.display());
    println!(
        "\nNext: edit the plan to add phases and tasks, then run `wiggum generate {}`",
        plan_path.display()
    );

    Ok(plan_path)
}

/// Scan a project directory without writing any files.
/// Used by both the CLI and MCP tool.
///
/// # Errors
///
/// Returns an error if the directory does not exist or no language can be detected.
pub fn scan_project(project_path: &Path) -> Result<ScanResult> {
    if !project_path.is_dir() {
        return Err(WiggumError::Validation(format!(
            "not a directory: {}",
            project_path.display()
        )));
    }

    let language = detect_language(project_path).ok_or_else(|| {
        WiggumError::Validation(
            "could not detect project language (no known manifest file found)".to_string(),
        )
    })?;

    let (name, description) = extract_manifest_info(project_path, language);
    let architecture = detect_architecture(project_path);
    let has_tests = detect_tests(project_path, language);
    let has_ci = project_path.join(".github/workflows").is_dir();

    let mut rules = Vec::new();
    if has_tests {
        rules.push("Existing test suite must remain green — do not break tests".to_string());
    }
    if let Some(ref arch) = architecture {
        rules.push(format!("Follow {arch} architecture patterns"));
    }

    // Check for existing AGENTS.md and extract rules from it
    let agents_md_path = project_path.join("AGENTS.md");
    if agents_md_path.is_file()
        && let Ok(content) = std::fs::read_to_string(&agents_md_path)
    {
        extract_agents_md_rules(&content, &mut rules);
    }

    Ok(ScanResult {
        language,
        name,
        description,
        architecture,
        rules,
        has_tests,
        has_ci,
    })
}

/// Build a Plan struct from scan results.
#[must_use]
pub fn build_plan_from_scan(scan: &ScanResult, project_path: &Path) -> Plan {
    let persona = format!("You are a senior {} software engineer", scan.language);

    let mut plan = Plan {
        project: Project {
            name: scan.name.clone(),
            description: scan.description.clone(),
            language: scan.language,
            path: project_path.to_string_lossy().to_string(),
            architecture: scan.architecture.clone(),
        },
        preflight: Preflight::default(),
        orchestrator: Orchestrator {
            persona,
            strategy: Strategy::default(),
            rules: scan.rules.clone(),
        },
        evaluator: None,
        security: crate::domain::plan::SecurityConfig::default(),
        phases: vec![Phase {
            name: "TODO — rename this phase".to_string(),
            order: 1,
            tasks: vec![TaskDef {
                slug: "first-task".to_string(),
                title: "TODO — describe first task".to_string(),
                goal: "TODO — what should this task accomplish?".to_string(),
                depends_on: vec![],
                hints: vec![],
                test_hints: vec![],
                must_haves: vec![],
                gate: None,
                evaluation_criteria: vec![],
            }],
        }],
    };
    plan.preflight = plan.preflight.with_defaults(scan.language);
    plan
}

// ─── Detection functions ────────────────────────────────────────────

fn detect_language(path: &Path) -> Option<Language> {
    // Check in priority order — more specific manifests first.
    if path.join("Cargo.toml").is_file() {
        Some(Language::Rust)
    } else if path.join("go.mod").is_file() {
        Some(Language::Go)
    } else if path.join("Package.swift").is_file() {
        Some(Language::Swift)
    } else if path.join("mix.exs").is_file() {
        Some(Language::Elixir)
    } else if path.join("build.gradle.kts").is_file() {
        Some(Language::Kotlin)
    } else if path.join("pom.xml").is_file() {
        Some(Language::Java)
    } else if path.join("pyproject.toml").is_file() {
        Some(Language::Python)
    } else if path.join("Gemfile").is_file() {
        Some(Language::Ruby)
    } else if has_file_matching(path, ".", ".csproj") {
        Some(Language::CSharp)
    } else if path.join("package.json").is_file() {
        Some(Language::TypeScript)
    } else {
        None
    }
}

fn extract_manifest_info(path: &Path, language: Language) -> (String, String) {
    match language {
        Language::Rust => extract_cargo_info(path),
        Language::TypeScript => extract_package_json_info(path),
        Language::Go => extract_go_mod_info(path),
        // Languages without rich manifest parsing fall back to the directory name.
        Language::Python
        | Language::Java
        | Language::CSharp
        | Language::Kotlin
        | Language::Swift
        | Language::Ruby
        | Language::Elixir => (dir_name_fallback(path), String::new()),
    }
}

fn extract_cargo_info(path: &Path) -> (String, String) {
    let cargo_path = path.join("Cargo.toml");
    let fallback_name = dir_name_fallback(path);

    let Ok(content) = std::fs::read_to_string(&cargo_path) else {
        return (fallback_name, String::new());
    };

    let Ok(doc) = content.parse::<toml::Table>() else {
        return (fallback_name, String::new());
    };

    let package = doc.get("package");
    let workspace_package = doc.get("workspace").and_then(|w| w.get("package"));

    let name = package
        .and_then(|p| p.get("name"))
        .or_else(|| workspace_package.and_then(|p| p.get("name")))
        .and_then(|v| v.as_str())
        .unwrap_or(&fallback_name)
        .to_string();

    let description = package
        .and_then(|p| p.get("description"))
        .or_else(|| workspace_package.and_then(|p| p.get("description")))
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    (name, description)
}

fn extract_package_json_info(path: &Path) -> (String, String) {
    let pkg_path = path.join("package.json");
    let fallback_name = dir_name_fallback(path);

    let Ok(content) = std::fs::read_to_string(&pkg_path) else {
        return (fallback_name, String::new());
    };

    let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) else {
        return (fallback_name, String::new());
    };

    let name = json
        .get("name")
        .and_then(|v| v.as_str())
        .unwrap_or(&fallback_name)
        .to_string();

    let description = json
        .get("description")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    (name, description)
}

fn extract_go_mod_info(path: &Path) -> (String, String) {
    let mod_path = path.join("go.mod");
    let fallback_name = dir_name_fallback(path);

    let Ok(content) = std::fs::read_to_string(&mod_path) else {
        return (fallback_name, String::new());
    };

    // Extract module path from "module github.com/user/repo"
    let name = content
        .lines()
        .find(|l| l.starts_with("module "))
        .and_then(|l| l.strip_prefix("module "))
        .map(|m| {
            // Use the last segment of the module path as the name
            m.rsplit('/').next().unwrap_or(m).to_string()
        })
        .unwrap_or(fallback_name);

    (name, String::new())
}

fn dir_name_fallback(path: &Path) -> String {
    path.file_name().map_or_else(
        || "project".to_string(),
        |n| n.to_string_lossy().to_string(),
    )
}

fn detect_architecture(path: &Path) -> Option<String> {
    let src = path.join("src");
    if !src.is_dir() {
        return None;
    }

    // Hexagonal signals
    let has_adapters = src.join("adapters").is_dir() || src.join("adapter").is_dir();
    let has_ports =
        src.join("ports").is_dir() || src.join("ports.rs").is_file() || src.join("port").is_dir();
    let has_domain = src.join("domain").is_dir();

    if has_adapters && (has_ports || has_domain) {
        return Some("hexagonal".to_string());
    }

    // Layered signals
    let has_infra = src.join("infrastructure").is_dir() || src.join("infra").is_dir();
    let has_app = src.join("application").is_dir() || src.join("app").is_dir();
    if has_domain && has_infra {
        return Some("layered".to_string());
    }
    if has_app && has_domain {
        return Some("layered".to_string());
    }

    // Modular signals (multiple peer directories, no clear layers)
    if let Ok(entries) = std::fs::read_dir(&src) {
        let dir_count = entries
            .filter_map(std::result::Result::ok)
            .filter(|e| e.path().is_dir())
            .count();
        if dir_count >= 3 {
            return Some("modular".to_string());
        }
    }

    None
}

fn detect_tests(path: &Path, language: Language) -> bool {
    match language {
        Language::Rust => path.join("tests").is_dir() || has_file_matching(path, "src", "_test.rs"),
        Language::TypeScript => {
            path.join("__tests__").is_dir()
                || path.join("tests").is_dir()
                || has_file_matching(path, "src", ".test.ts")
                || has_file_matching(path, "src", ".spec.ts")
        }
        Language::Go => has_file_matching(path, ".", "_test.go"),
        Language::Python => path.join("tests").is_dir() || has_file_matching(path, ".", "test_"),
        Language::Java | Language::Kotlin => path.join("src/test").is_dir(),
        Language::CSharp => has_file_matching(path, ".", "Tests.cs"),
        Language::Swift => path.join("Tests").is_dir(),
        Language::Ruby => path.join("spec").is_dir() || path.join("test").is_dir(),
        Language::Elixir => path.join("test").is_dir(),
    }
}

/// Check if any file in a subdirectory has a given suffix.
/// Only checks one level deep to avoid slow recursive scans.
fn has_file_matching(base: &Path, subdir: &str, suffix: &str) -> bool {
    let dir = base.join(subdir);
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return false;
    };
    entries.filter_map(std::result::Result::ok).any(|e| {
        e.path()
            .file_name()
            .is_some_and(|n| n.to_string_lossy().ends_with(suffix))
    })
}

/// Extract rule-like lines from an existing AGENTS.md file.
/// Looks for lines starting with "- " under rule-like sections.
fn extract_agents_md_rules(content: &str, rules: &mut Vec<String>) {
    let mut in_rules_section = false;
    for line in content.lines() {
        if line.starts_with("## Rules") || line.starts_with("## Code style") {
            in_rules_section = true;
            continue;
        }
        if line.starts_with("## ") {
            in_rules_section = false;
            continue;
        }
        if in_rules_section && let Some(rule) = line.strip_prefix("- ") {
            let rule = rule.trim();
            if !rule.is_empty() {
                rules.push(rule.to_string());
            }
        }
    }
}

fn print_scan_summary(scan: &ScanResult, project_path: &Path) {
    println!(
        "🦝 wiggum bootstrap — scanning {}\n",
        project_path.display()
    );
    println!("  Detected:");
    println!("    Language:     {}", scan.language);
    println!("    Name:         {}", scan.name);
    if !scan.description.is_empty() {
        println!("    Description:  \"{}\"", scan.description);
    }
    if let Some(ref arch) = scan.architecture {
        println!("    Architecture: {arch}");
    }
    if scan.has_tests {
        println!("    Tests:        found");
    }
    if scan.has_ci {
        println!("    CI:           .github/workflows/ found");
    }
    if !scan.rules.is_empty() {
        println!("    Rules:        {} inferred", scan.rules.len());
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::indexing_slicing)]
mod tests {
    use super::*;
    use std::fs;

    fn setup_temp_dir() -> tempfile::TempDir {
        tempfile::TempDir::new().unwrap()
    }

    #[test]
    fn detect_rust_language() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("Cargo.toml"),
            "[package]\nname = \"my-crate\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::Rust));
    }

    #[test]
    fn detect_typescript_language() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("package.json"),
            r#"{"name": "my-app", "version": "1.0.0"}"#,
        )
        .unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::TypeScript));
    }

    #[test]
    fn detect_go_language() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("go.mod"),
            "module github.com/user/my-tool\n\ngo 1.21\n",
        )
        .unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::Go));
    }

    #[test]
    fn detect_no_language() {
        let dir = setup_temp_dir();
        assert_eq!(detect_language(dir.path()), None);
    }

    #[test]
    fn rust_takes_priority_over_others() {
        let dir = setup_temp_dir();
        fs::write(dir.path().join("Cargo.toml"), "[package]\nname = \"x\"\n").unwrap();
        fs::write(dir.path().join("package.json"), r#"{"name": "x"}"#).unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::Rust));
    }

    #[test]
    fn extract_cargo_name_and_description() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("Cargo.toml"),
            "[package]\nname = \"wiggum\"\ndescription = \"AI orchestrator\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();
        let (name, desc) = extract_cargo_info(dir.path());
        assert_eq!(name, "wiggum");
        assert_eq!(desc, "AI orchestrator");
    }

    #[test]
    fn extract_cargo_workspace_info() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("Cargo.toml"),
            "[workspace]\nmembers = [\"crates/*\"]\n\n[workspace.package]\nname = \"mono\"\ndescription = \"A monorepo\"\n",
        )
        .unwrap();
        let (name, desc) = extract_cargo_info(dir.path());
        assert_eq!(name, "mono");
        assert_eq!(desc, "A monorepo");
    }

    #[test]
    fn extract_package_json_info_works() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("package.json"),
            r#"{"name": "@acme/widget", "description": "Widget factory"}"#,
        )
        .unwrap();
        let (name, desc) = extract_package_json_info(dir.path());
        assert_eq!(name, "@acme/widget");
        assert_eq!(desc, "Widget factory");
    }

    #[test]
    fn extract_go_mod_name() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("go.mod"),
            "module github.com/user/my-service\n\ngo 1.21\n",
        )
        .unwrap();
        let (name, _desc) = extract_go_mod_info(dir.path());
        assert_eq!(name, "my-service");
    }

    #[test]
    fn detect_hexagonal_architecture() {
        let dir = setup_temp_dir();
        let src = dir.path().join("src");
        fs::create_dir_all(src.join("adapters")).unwrap();
        fs::create_dir_all(src.join("domain")).unwrap();
        assert_eq!(
            detect_architecture(dir.path()),
            Some("hexagonal".to_string())
        );
    }

    #[test]
    fn detect_layered_architecture() {
        let dir = setup_temp_dir();
        let src = dir.path().join("src");
        fs::create_dir_all(src.join("domain")).unwrap();
        fs::create_dir_all(src.join("infrastructure")).unwrap();
        assert_eq!(detect_architecture(dir.path()), Some("layered".to_string()));
    }

    #[test]
    fn detect_modular_architecture() {
        let dir = setup_temp_dir();
        let src = dir.path().join("src");
        fs::create_dir_all(src.join("auth")).unwrap();
        fs::create_dir_all(src.join("billing")).unwrap();
        fs::create_dir_all(src.join("notifications")).unwrap();
        assert_eq!(detect_architecture(dir.path()), Some("modular".to_string()));
    }

    #[test]
    fn detect_no_architecture_without_src() {
        let dir = setup_temp_dir();
        assert_eq!(detect_architecture(dir.path()), None);
    }

    #[test]
    fn detect_tests_rust() {
        let dir = setup_temp_dir();
        fs::create_dir_all(dir.path().join("tests")).unwrap();
        assert!(detect_tests(dir.path(), Language::Rust));
    }

    #[test]
    fn detect_tests_typescript() {
        let dir = setup_temp_dir();
        fs::create_dir_all(dir.path().join("__tests__")).unwrap();
        assert!(detect_tests(dir.path(), Language::TypeScript));
    }

    #[test]
    fn detect_no_tests() {
        let dir = setup_temp_dir();
        assert!(!detect_tests(dir.path(), Language::Rust));
    }

    #[test]
    fn extract_agents_md_rules_works() {
        let content = "# AGENTS.md\n\n## Rules\n\n- No unwrap\n- Use thiserror\n\n## Testing\n\n- Run tests\n";
        let mut rules = Vec::new();
        extract_agents_md_rules(content, &mut rules);
        assert_eq!(rules, vec!["No unwrap", "Use thiserror"]);
    }

    #[test]
    fn extract_agents_md_code_style_rules() {
        let content = "## Code style\n\n- Language: Rust\n- Strategy: TDD\n\n## Other\n";
        let mut rules = Vec::new();
        extract_agents_md_rules(content, &mut rules);
        assert_eq!(rules, vec!["Language: Rust", "Strategy: TDD"]);
    }

    #[test]
    fn build_plan_populates_all_fields() {
        let scan = ScanResult {
            language: Language::Rust,
            name: "my-project".to_string(),
            description: "A cool project".to_string(),
            architecture: Some("hexagonal".to_string()),
            rules: vec!["rule one".to_string()],
            has_tests: true,
            has_ci: true,
        };
        let plan = build_plan_from_scan(&scan, Path::new("/tmp/my-project"));
        assert_eq!(plan.project.name, "my-project");
        assert_eq!(plan.project.description, "A cool project");
        assert_eq!(plan.project.language, Language::Rust);
        assert_eq!(plan.project.architecture.as_deref(), Some("hexagonal"));
        assert_eq!(plan.orchestrator.rules, vec!["rule one"]);
        assert!(!plan.preflight.build.is_empty());
        assert_eq!(plan.phases.len(), 1);
        assert_eq!(plan.phases[0].tasks.len(), 1);
    }

    #[test]
    fn scan_project_detects_rust() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("Cargo.toml"),
            "[package]\nname = \"test-crate\"\nversion = \"0.1.0\"\ndescription = \"Test\"\n",
        )
        .unwrap();
        fs::create_dir_all(dir.path().join("tests")).unwrap();

        let scan = scan_project(dir.path()).unwrap();
        assert_eq!(scan.language, Language::Rust);
        assert_eq!(scan.name, "test-crate");
        assert_eq!(scan.description, "Test");
        assert!(scan.has_tests);
    }

    #[test]
    fn scan_project_fails_on_missing_dir() {
        let result = scan_project(Path::new("/nonexistent/path/12345"));
        assert!(result.is_err());
    }

    #[test]
    fn scan_project_fails_on_no_language() {
        let dir = setup_temp_dir();
        let result = scan_project(dir.path());
        assert!(result.is_err());
    }

    #[test]
    fn run_bootstrap_writes_plan() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("Cargo.toml"),
            "[package]\nname = \"boot-test\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();

        let out = dir.path().join("plan.toml");
        let result = run_bootstrap(dir.path(), Some(&out), false);
        assert!(result.is_ok());
        assert!(out.exists());

        let content = fs::read_to_string(&out).unwrap();
        assert!(content.contains("boot-test"));
        assert!(content.contains("wiggum bootstrap"));
    }

    #[test]
    fn run_bootstrap_refuses_overwrite_without_force() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("Cargo.toml"),
            "[package]\nname = \"x\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();

        let out = dir.path().join("plan.toml");
        fs::write(&out, "existing").unwrap();

        let result = run_bootstrap(dir.path(), Some(&out), false);
        assert!(result.is_err());
        // Original content preserved
        assert_eq!(fs::read_to_string(&out).unwrap(), "existing");
    }

    #[test]
    fn run_bootstrap_allows_overwrite_with_force() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("Cargo.toml"),
            "[package]\nname = \"forced\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();

        let out = dir.path().join("plan.toml");
        fs::write(&out, "existing").unwrap();

        let result = run_bootstrap(dir.path(), Some(&out), true);
        assert!(result.is_ok());
        let content = fs::read_to_string(&out).unwrap();
        assert!(content.contains("forced"));
    }

    #[test]
    fn detect_python_language() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("pyproject.toml"),
            "[project]\nname = \"x\"\n",
        )
        .unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::Python));
    }

    #[test]
    fn detect_java_language() {
        let dir = setup_temp_dir();
        fs::write(dir.path().join("pom.xml"), "<project></project>").unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::Java));
    }

    #[test]
    fn detect_kotlin_language() {
        let dir = setup_temp_dir();
        fs::write(dir.path().join("build.gradle.kts"), "plugins {}").unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::Kotlin));
    }

    #[test]
    fn detect_swift_language() {
        let dir = setup_temp_dir();
        fs::write(
            dir.path().join("Package.swift"),
            "// swift-tools-version:5.9",
        )
        .unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::Swift));
    }

    #[test]
    fn detect_ruby_language() {
        let dir = setup_temp_dir();
        fs::write(dir.path().join("Gemfile"), "source 'https://rubygems.org'").unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::Ruby));
    }

    #[test]
    fn detect_elixir_language() {
        let dir = setup_temp_dir();
        fs::write(dir.path().join("mix.exs"), "defmodule MyApp.MixProject do").unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::Elixir));
    }

    #[test]
    fn detect_csharp_language() {
        let dir = setup_temp_dir();
        fs::write(dir.path().join("MyApp.csproj"), "<Project></Project>").unwrap();
        assert_eq!(detect_language(dir.path()), Some(Language::CSharp));
    }

    #[test]
    fn detect_tests_python() {
        let dir = setup_temp_dir();
        fs::create_dir_all(dir.path().join("tests")).unwrap();
        assert!(detect_tests(dir.path(), Language::Python));
    }

    #[test]
    fn detect_tests_java() {
        let dir = setup_temp_dir();
        fs::create_dir_all(dir.path().join("src/test")).unwrap();
        assert!(detect_tests(dir.path(), Language::Java));
    }

    #[test]
    fn detect_tests_ruby() {
        let dir = setup_temp_dir();
        fs::create_dir_all(dir.path().join("spec")).unwrap();
        assert!(detect_tests(dir.path(), Language::Ruby));
    }

    #[test]
    fn detect_tests_elixir() {
        let dir = setup_temp_dir();
        fs::create_dir_all(dir.path().join("test")).unwrap();
        assert!(detect_tests(dir.path(), Language::Elixir));
    }

    #[test]
    fn detect_tests_swift() {
        let dir = setup_temp_dir();
        fs::create_dir_all(dir.path().join("Tests")).unwrap();
        assert!(detect_tests(dir.path(), Language::Swift));
    }

    #[test]
    fn new_languages_fallback_to_dir_name() {
        let dir = setup_temp_dir();
        let (name, desc) = extract_manifest_info(dir.path(), Language::Python);
        assert!(!name.is_empty());
        assert!(desc.is_empty());
    }
}
